# Authentifizierung
@host = {{host}}

###
# @name authLoginForm
GET {{host}}/login

?? status == 200
?? body includes Einloggen

###
# @name authLoginPage
GET {{host}}/login

{{
  exports.loginCsrf = response.body.match(/name="_csrf" value="([^"]+)"/)[1];
}}

###
# @no-redirect
# @name authLoginOk
POST {{host}}/login
Content-Type: application/x-www-form-urlencoded

username={{testUser}}&password={{testPassword}}&_csrf={{loginCsrf}}

?? status == 302
?? header location == /

###
# @name authSessionCheck
GET {{host}}/

?? status == 200
?? body includes tyrion_fan

{{
  exports.homeCsrf = response.body.match(/name="csrf-token" content="([^"]+)"/)[1];
}}

###
# @no-redirect
# @name authLogout
POST {{host}}/logout
X-CSRF-Token: {{homeCsrf}}

?? status == 302

###
# @no-redirect
# @name authProfileRedirect
GET {{host}}/profile

?? status == 302
?? header location == /login

###
# @name authBadLoginPage
GET {{host}}/login

{{
  exports.badCsrf = response.body.match(/name="_csrf" value="([^"]+)"/)[1];
}}

###
# @name authLoginFail
POST {{host}}/login
Content-Type: application/x-www-form-urlencoded

username={{testUser}}&password=wrongpassword&_csrf={{badCsrf}}

?? status == 200
?? body includes ungültig
