# Administration (Admin)
@host = {{host}}

###
# @name admLoginPage
GET {{host}}/login

{{
  exports.adminCsrf = response.body.match(/name="_csrf" value="([^"]+)"/)[1];
}}

###
# @name admLoginOk
POST {{host}}/login
Content-Type: application/x-www-form-urlencoded

username={{adminUser}}&password={{adminPassword}}&_csrf={{adminCsrf}}

###
# @name admUserList
GET {{host}}/admin/users

?? status == 200
?? body includes Benutzer

###
# @name admQuoteList
GET {{host}}/admin/quotes

?? status == 200
?? body includes Zitate

###
# @name admQuoteNewForm
GET {{host}}/admin/quotes/new

?? status == 200
?? body includes Anlegen

###
# @name admUserLoginPage
GET {{host}}/login

{{
  exports.userCsrf = response.body.match(/name="_csrf" value="([^"]+)"/)[1];
}}

###
# @name admUserLoginOk
POST {{host}}/login
Content-Type: application/x-www-form-urlencoded

username={{testUser}}&password={{testPassword}}&_csrf={{userCsrf}}

###
# @no-redirect
# @name admUserForbidden
GET {{host}}/admin/users

?? status == 403
