# Likes, Votes, REST-Methoden
@host = {{host}}

###
# @name forumLoginPage
GET {{host}}/login

{{
  exports.csrf = response.body.match(/name="_csrf" value="([^"]+)"/)[1];
}}

###
# @name forumLoginOk
POST {{host}}/login
Content-Type: application/x-www-form-urlencoded

username={{testUser}}&password={{testPassword}}&_csrf={{csrf}}

###
# @name forumQuoteLike
GET {{host}}/quotes/2

{{
  exports.likeCsrf = response.body.match(/name="csrf-token" content="([^"]+)"/)[1];
}}

###
# @no-redirect
# @name forumLike
POST {{host}}/quotes/2/likes
X-CSRF-Token: {{likeCsrf}}

?? status == 302

###
# @name forumQuoteUnlike
GET {{host}}/quotes/2

{{
  exports.unlikeCsrf = response.body.match(/name="csrf-token" content="([^"]+)"/)[1];
}}

###
# @no-redirect
# @name forumUnlike
DELETE {{host}}/quotes/2/likes
X-CSRF-Token: {{unlikeCsrf}}

?? status == 302

###
# @name forumQuoteVote
GET {{host}}/quotes/1

{{
  exports.voteCsrf = response.body.match(/name="csrf-token" content="([^"]+)"/)[1];
}}

###
# @no-redirect
# @name forumUpvote
POST {{host}}/comments/3/votes
Content-Type: application/x-www-form-urlencoded
X-CSRF-Token: {{voteCsrf}}

vote=1

?? status == 302

###
# @name forumQuoteRemoveVote
GET {{host}}/quotes/1

{{
  exports.removeVoteCsrf = response.body.match(/name="csrf-token" content="([^"]+)"/)[1];
}}

###
# @no-redirect
# @name forumRemoveVote
DELETE {{host}}/comments/3/votes
X-CSRF-Token: {{removeVoteCsrf}}

?? status == 302

###
# @no-redirect
# @name forumDeleteNoCsrf
DELETE {{host}}/comments/1

?? status == 302
?? header location == /

###
# @name forumHomeBadLike
GET {{host}}/

{{
  exports.badLikeCsrf = response.body.match(/name="csrf-token" content="([^"]+)"/)[1];
}}

###
# @no-redirect
# @name forumBadLike
POST {{host}}/quotes/99999/likes
X-CSRF-Token: {{badLikeCsrf}}

?? status == 404
